NewTec-GmbH/pyJiraCli

README.md, pyproject.toml, setup.cfg, src/pyJiraCli/__main__.py
=> Enable the Windows built-in ANSI color code support.

src/pyJiraCli/cmd_export.py, src/pyJiraCli/jira_server.py, src/pyJiraCli/printer.py, src/pyJiraCli/ret.py
The default server url removed, because the tool shall be generic and is open source.
#19
=> Remove default server URL

README.md, src/pyJiraCli/__main__.py, src/pyJiraCli/cmd_delete.py, src/pyJiraCli/cmd_export.py, src/pyJiraCli/cmd_import.py, src/pyJiraCli/cmd_login.py, src/pyJiraCli/cmd_print.py, src/pyJiraCli/cmd_search.py
Improved CLI command arguments and descriptions.
=> Improved CLI

README.md, src/pyJiraCli/__main__.py, src/pyJiraCli/cmd_delete.py, src/pyJiraCli/cmd_export.py, src/pyJiraCli/cmd_import.py, src/pyJiraCli/cmd_login.py, src/pyJiraCli/cmd_print.py, src/pyJiraCli/cmd_search.py, src/pyJiraCli/crypto_file_handler.py, src/pyJiraCli/file_handler.py, src/pyJiraCli/jira_issue.py, src/pyJiraCli/jira_server.py, src/pyJiraCli/printer.py, src/pyJiraCli/ret.py, tests/test_main.py
Moved return and warning messages to ret.py.
Encapsulation of messges and codes into dataclasses
=> Return codes and messages

src/pyJiraCli/cmd_import.py, src/pyJiraCli/cmd_print.py, src/pyJiraCli/cmd_search.py, src/pyJiraCli/jira_server.py
rmove unused logout() function from jira_server class and all calls to it.
=> close issue #51

README.md, design/context.puml, design/use_case.puml
=> update the documentation

src/pyJiraCli/issue_constants.py, src/pyJiraCli/jira_issue.py
remove unused constants
close #2
=> use the raw issue dict for export, print and search

README.md, design/context.puml, pyproject.toml, setup.cfg, src/pyJiraCli/__main__.py, src/pyJiraCli/cmd_export.py, src/pyJiraCli/cmd_print.py, src/pyJiraCli/file_handler.py, src/pyJiraCli/ret.py
=> 47 drop csv support

src/pyJiraCli/cmd_profile.py
=> close issue 

src/pyJiraCli/ret.py
=> fix errors

src/pyJiraCli/cmd_export.py, src/pyJiraCli/file_handler.py, src/pyJiraCli/jira_server.py, src/pyJiraCli/profile_handler.py
=> 68 profile command not working under linux

README.md, src/pyJiraCli/__main__.py, src/pyJiraCli/cmd_export.py, src/pyJiraCli/cmd_get_sprints.py, src/pyJiraCli/cmd_import.py, src/pyJiraCli/cmd_print.py, src/pyJiraCli/cmd_profile.py, src/pyJiraCli/cmd_search.py, src/pyJiraCli/jira_server.py, tests/test_main.py
Server login is handled by the main entry point, and passed as an argument to the individual commands.
Commands can use the server functions but do not care about logging into the server.
=> Refactoring

examples/import_issues/README.md, examples/import_issues/component.json, src/pyJiraCli/cmd_import.py
=> Feature: create component

.github/workflows/ci.yml, .github/workflows/online.yml, pyproject.toml
=> Added Python 3.11 support

src/pyJiraCli/cmd_search.py
Closes #78 
Feature was implemented but this specific behaviour was not documented.
=> Improved max option documentation

examples/scripts/README.md, examples/scripts/track_sprint_progress/README.md, examples/scripts/track_sprint_progress/track_sprint_progress.py, examples/sprints/README.md, examples/sprints/sprints_in_board.json
=> 89 examples for get sprints

pyproject.toml, src/pyJiraCli/cmd_import.py
=> Fixed exception on existing components

pyproject.toml, src/pyJiraCli/cmd_search.py
=> Get complete worklog from issues when searching.

README.md, examples/scripts/track_sprint_progress/README.md, examples/scripts/track_sprint_progress/track_sprint_progress.py, examples/search/README.md, src/pyJiraCli/cmd_search.py, tests/online/test_04_search.py
=> Different parameters for the same

README.md, src/pyJiraCli/cmd_export.py, src/pyJiraCli/cmd_print.py, src/pyJiraCli/cmd_search.py, src/pyJiraCli/jira_server.py, tests/online/test_04_search.py
Added filtering of search queries by specifiying which fields are to be retrieved and printed.
=> Feature: filter search

examples/import_issues/README.md
=> Add a short description regarding custom fields.

.github/workflows/ci.yml, .github/workflows/online.yml, LICENSE, README.md, pyproject.toml, setup.cfg, setup.py, src/pyJiraCli/__init__.py, src/pyJiraCli/__main__.py, src/pyJiraCli/cmd_export.py, src/pyJiraCli/cmd_get_sprints.py, src/pyJiraCli/cmd_import.py, src/pyJiraCli/cmd_print.py, src/pyJiraCli/cmd_profile.py, src/pyJiraCli/cmd_search.py, src/pyJiraCli/file_handler.py, src/pyJiraCli/jira_server.py, src/pyJiraCli/print_type.py, src/pyJiraCli/printer.py, src/pyJiraCli/profile_handler.py, src/pyJiraCli/ret.py, src/pyJiraCli/version.py, tests/conftest.py, tests/offline/test_help.py, tests/online/test_01_profile.py, tests/online/test_02_import_export.py, tests/online/test_03_print.py, tests/online/test_04_search.py, tests/online/test_05_get_sprints.py, tests/tools/setup_jira_server.py
Additional copyright year updated.
=> Support for Python v3.12 and v.3.13

src/pyJiraCli/__main__.py, src/pyJiraCli/cmd_profile.py, src/pyJiraCli/ret.py
Fix profile add by not trying to load the profile that does not yet exist. 
Fix _check_profile by removing unavailable arguments. 
Improve profile remove by not checking the profile that is scheduled for removal anyways.
=> Fix multiple bugs in profile cmd.

README.md, doc/uml/context.puml
Some documentation (puml) updates found during my initial trials with the tool.
=> Minor documentation updates

src/pyJiraCli/profile_handler.py, tests/online/test_02_import_export.py, tests/online/test_03_print.py, tests/online/test_04_search.py, tests/online/test_05_get_sprints.py
Pytests fail (locally) without these changes.
I wonder why they show green in the pipeline anyway?
test_05 hasn't been tackled (I have no rights to create sprints in Jira).
Edit: Fixed now as well
=> Pytest bugfixes
